# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.useOSProber = false;
  boot.loader.grub.enableCryptodisk = true;
  boot.loader.grub.copyKernels = true;
  boot.loader.grub.extraGrubInstallArgs = [
#    "--verbose"
    "--modules=nativedisk part_gpt diskfilter lvm mdraid1x"
  ];
  boot.loader.grub.extraEntries = ''
    menuentry Windows {
      insmod part_gpt
      insmod fat
      insmod search_fs_uuid
      insmod chain
      search --fs-uuid --set=root 6FA7-FA84
      chainloader /EFI/Microsoft/Boot/bootmgfw.efi
    }
    '';

  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "nvme" ];
  boot.initrd.supportedFilesystems = [ "btrfs" "ext4" "vfat" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "dm-integrity" "dm-raid" "nvidia" ];
  boot.initrd.systemd.enable = true;
  boot.initrd.services.lvm.enable = true;
  boot.swraid.enable = true;
  boot.initrd.systemd.contents =
    {
      "/etc/lvm/lvm.conf".source = ./files/lvm.conf;
    };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.nvidia_x11 ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e8c01229-6f85-482c-a89c-5a15f7b9892b";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
      encrypted =
        {
          enable = true;
          blkDev = "/dev/disk/by-uuid/22d33bf1-e4ad-4fb3-bdc7-c1a6e2244206";
          label  = "main_os_crypt";
        };
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2a4b3410-ef8a-4d29-9adf-d9a01e3ac495";
      fsType = "ext4";
      encrypted =
        {
          enable = true;
          blkDev = "/dev/disk/by-uuid/2d47987a-cf3d-4693-bb18-d0c8312d2924";
          label  = "main_os_crypt";
        };
    };

  boot.initrd.luks.devices."main_os_crypt".device = "/dev/disk/by-uuid/22d33bf1-e4ad-4fb3-bdc7-c1a6e2244206";
  #boot.initrd.luks.devices."main_boot_crypt".device = "/dev/disk/by-uuid/2d47987a-cf3d-4693-bb18-d0c8312d2924";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/6FA7-FA84";
      fsType = "vfat";
      #options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e8c01229-6f85-482c-a89c-5a15f7b9892b";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e8c01229-6f85-482c-a89c-5a15f7b9892b";
      fsType = "btrfs";
      options = [ "subvol=@var-log" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fad5a2a6-de92-4458-a335-55d182b087b9";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home/.snapshots" =
    { device = "/dev/disk/by-uuid/fad5a2a6-de92-4458-a335-55d182b087b9";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  environment.etc."crypttab".text = ''
    main_os_crypt     UUID=22d33bf1-e4ad-4fb3-bdc7-c1a6e2244206    none
    main_boot_crypt   UUID=2d47987a-cf3d-4693-bb18-d0c8312d2924    /root/boot.key
    main_perf_crypt   UUID=37f3cacc-5b3e-4dc4-8839-fb1b29078391    /root/perf.key
  '';

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e0358e18-7b60-4ea6-8d91-de0780b82e46"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
