#!/usr/bin/env bash

new_prefix="$1"

if [[ $# -eq 1 ]]
then
  source_branches=("$(git branch --show-current)")
else
  shift 1
  source_branches=("$@")
fi

for branch in "${source_branches[@]}"
do
  suffix="$(echo "${branch}" | rg -e '^(_\w+-)?(.*)$' -o -r '$2')"
  git branch --move "${branch}" "_${new_prefix}-${suffix}"
done

