#!/usr/bin/env bash

remote_name="$1"
shift 1
exclude_refs_re="$1"

remote_refs=$(git ls-remote --heads --tags "$remote_name" | awk '{print $2}' | \
  rg -v "$exclude_refs_re" | sort)

local_refs=$(git for-each-ref --format='%(refname)' \
  "refs/tags/" "refs/heads/" |                      \
  rg -v "$exclude_refs_re" | sort )

delete_refs="$(comm -13 <(echo "$local_refs") <(echo "$remote_refs"))"

if [ "$delete_refs" != "" ]
then
  # shellcheck disable=SC2086
  git push --delete "$remote_name" $delete_refs
fi
# shellcheck disable=SC2086
git push --force --prune "$remote_name" $local_refs
